apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "file-watcher.fullname" . }}
  labels:
    {{- include "file-watcher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "file-watcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "file-watcher.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      containers:
        - name: inotify-k8s-daemon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}