apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "file-watcher.fullname" . }}
  labels:
    {{- include "file-watcher.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "file-watcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "file-watcher.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      containers:
        - name: inotify-k8s-daemon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          env:
            - name: SOURCE_SUBPATH
              value: {{ .Values.subpaths.source.path }}
            - name: TARGET_SUBPATH
              value: {{ .Values.subpaths.target.path }}
            - name: DEBUG_LEVEL
              {{- if .Values.debug }}
              value: DEBUG
              {{- else }}
              value: INFO
              {{- end }}
            - name: CREATE_SUBPATHS_SOURCE
              {{- if .Values.subpaths.source.create }}
              value: "True"
              {{- else }}
              value: "False"
              {{- end }}
            - name: CREATE_SUBPATHS_TARGET
              {{- if .Values.subpaths.target.create }}
              value:  "True"
              {{- else }}
              value: "False"
              {{- end }}
            - name: RECURSIVE
              {{- if .Values.recursive }}
              value:  "True"
              {{- else }}
              value: "False"
              {{- end }}
            - name: POLLING_OBSERVER
              {{- if .Values.usePollingObserver }}
              value: "True"
              {{- else }}
              value: "False"
              {{- end }}
            - name: RETRY_LIMIT
              value: '{{ .Values.maxRetries }}'

      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}