# values.yaml
image:
  repository: stainlessai/inotify-k8s-daemon
  tag: latest
  pullPolicy: Always

# Resource limits
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Default volumes and mounts
volumes:
  - name: source-dir
    emptyDir:
      sizeLimit: 500Mi
  - name: target-dir
    emptyDir:
      sizeLimit: 500Mi

volumeMounts:
  - name: source-dir
    mountPath: /watch/source
  - name: target-dir
    mountPath: /watch/target

# Extra volumes and mounts that can be added through values
extraVolumes: []
extraVolumeMounts: []
