# values.yaml
image:
  repository: stainlessai/inotify-k8s-daemon
  tag: latest
  pullPolicy: Always

# Resource limits
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Default volumes and mounts
volumes:
  - name: source-dir
    emptyDir:
      sizeLimit: 500Mi
  - name: target-dir
    emptyDir:
      sizeLimit: 500Mi

volumeMounts:
  - name: source-dir
    mountPath: /watch/source_root
  - name: target-dir
    mountPath: /watch/target_root

subpaths:
  source:
    create: false
    path: '/create/me'
  target:
    create: false
    path: '/create/me/too'

debug: false

# Watch subdirectories of source also
recursive: true

# TODO implement: run rsync on startup
sync_on_startup: false

# Extra volumes and mounts that can be added through values
extraVolumes: []
extraVolumeMounts: []
